LOCAL_PATH := $(call my-dir)/..

include $(CLEAR_VARS)

LOCAL_SRC_FILES := sqlite3.c

LOCAL_MODULE := sqlite3

LOCAL_CFLAGS := -DSQLITE_ENABLE_FTS4 -D_FILE_OFFSET_BITS=32 \
	-DSQLITE_DEBUG=1 -DSQLITE_FORCE_OS_TRACE=1 -DSQLITE_DEBUG_OS_TRACE=1 \
	-DSQLITE_LOCK_TRACE=1 -DSQLITE_OMIT_WAL=1

include $(BUILD_SHARED_LIBRARY)
